# MySQL Database Connection Configuration

MYSQL_HOST = "spotty-candles-share.loca.lt"  # Replace with your MySQL host
MYSQL_USER = "root"                       # Replace with your MySQL username
MYSQL_PASSWORD = "root"                   # Replace with your MySQL password
MYSQL_DB = "webapp"                       # Replace with your MySQL database name
MYSQL_PORT = "3306"                       # MySQL port
