# MySQL Database Connection Configuration

MYSQL_HOST = "brown-bears-film.loca.lt"       # Replace with your MySQL host (e.g., "your-db-host.amazonaws.com" or "localhost" if using Ngrok)
MYSQL_USER = "root"          # Replace with your MySQL username
MYSQL_PASSWORD = "root"      # Replace with your MySQL password
MYSQL_DB = "webapp"            # Replace with your MySQL database name
